### PR TITLE
Edit founders allocation

### LINKED ISSUE #142: [Admin] Add the ability to edit founder allocation
**Background**
DAOs can currently submit a proposal to edit founders allocation but only via Etherscan. 

**Additional information**
- It looks like the NFT contract is where the edits can be made (e.g. [BuilderDAO example](https://etherscan.io/address/0xdf9b7d26c8fc806b1ae6273684556761ff02d422#readProxyContract))
- Items 9, 26 and 27 are relevant

### LINKED ISSUE #174: [Admin settings] Visually separate setting items
**Is your feature request related to a problem? Please describe.**
Items on admin settings tab are not presented in a UX-friendly way. They are listed in a simple format which can cause confusion to users trying to edit admin settings.

**Describe the solution you'd like**
Add visual changes to separate or group items together on the Admin settings page

A possible solution [(Figma link)](https://www.figma.com/file/gyRt2DgZobN8HwobPnxLrA/Nouns-Builder-Designs---Public?node-id=7343-19959&t=lekiWSc3epr3v5OE-4)
image

### PR DESCRIPTION
**Pull request by neokry**
## Description

Allows editing founders allocation on admin page

## Motivation & context

close #142
closes #174

## Code review

- are transactions being created correctly?
- does the form validate allocations properly?
- should we create a generic version of `FounderAllocationFields.tsx` that works with both admin and create pages?
- should visually separate this part of the form to help ux?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Comment by isaaczaak** [comment]
Screenshot 2023-03-27 at 8 13 00 pm

Error message here should show "Must be whole number" when the input value is 0.X

**Comment by isaaczaak** [comment]
> should visually separate this part of the form to help ux?

Issue created to address this issue @neokry 
#174

**Comment by neokry** [comment]
Pushed more changes that close #174 as well @isaaczaak

**Review by isaaczaak — APPROVED** [review]
tested and meets acceptance criteria ✅

Given I want to edit DAO founders allocation, when I enter new allocation values on the Admin tab, then I can create a DAO proposal with a transaction that reflects the allocation changes.

**Review by ninazo — APPROVED** [review]
lgtm 👍

**Pull request merged**
