### PR TITLE
Add proposal template pause auction

### LINKED ISSUE #131: PROP TEMPLATE: Pause auctions

### PR DESCRIPTION
**Pull request by neokry**
## Description

Adds a new proposal template for pausing auctions.

## Motivation & context

closes #131 

## Code review

Was unsure of how to handle the button click if the auctions are already paused. Should we display an error message or not even show that template option in the first place? Currently the button click does nothing if auctions are paused already.

Should I be using a form for the button submission like the other components? Seems like overkill for this so I left it out but happy to keep things consistent.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Comment by nadiakiamilev** [comment]
a couple of comments! this looks good!

-- error message if auction is currently paused - what about disabling the button and adding a message that indicates that the auction is already paused? we similarly do this if a user attempts to do an airdrop while an upgrade proposal is currently active - the form is disabled and we display an error message that they can't access the feature until the upgrade proposal has gone through. might be worth to check in with @isaaczaak if you haven't already!
-- form - i think it makes sense that this one isn't a form- as it's just a button and there are not input values to handle or manage. 
-- do we know how the app behaves when an auction is paused? ie what happens to the token page? We actually not might be gracefully handling paused auctions so it might be worth a pass to ensure that the token pages are functioning ok if an auction is paused. I'm not sure if we've handled this case just yet or have had a dao that has yet handled this case.

**Comment by neokry** [comment]
Thanks for the review @nadiakiamilev added an error message / disabled the button for when auctions are paused. Let me know if the copy on this is okay @isaaczaak 

Screen Shot 2023-03-14 at 11 11 48 AM

Also created a new issue for us to gracefully handle paused auctions #135 . This seemed beyond the scope of the proposal template so wanted to create a new issue for it.

**Review by nadiakiamilev — APPROVED** [review]
this looks great! nice one!

**Comment by nadiakiamilev** [comment]
any chance we might want to add helper text above the add transaction button? feels a bit blank but that's just my 2cents! cc @isaaczaak 

other than that looks great!

**Comment by isaaczaak** [comment]
@nadiakiamilev do you mean repositioning the helper text so it sits just above the button?

**Comment by nadiakiamilev** [comment]
> @nadiakiamilev do you mean repositioning the helper text so it sits just above the button?

in the state where you can pause (not the error state displayed by @neokry's screenshot), it just displays the button 'add transaction to queue' only, not sure if it feels a bit empty because there is no form in this template, so was wondering if some helper text would add to context here - but maybe it's not a big deal!

**Comment by isaaczaak** [comment]
agreed. how about this as the help text:

No further input required for this transaction

@neokry @nadiakiamilev

**Comment by neokry** [comment]
> agreed. how about this as the help text:
> 
> No further input required for this transaction
> 
> @neokry @nadiakiamilev

just added this helper text. let me know if size / color should be different @isaaczaak 

Screen Shot 2023-03-15 at 10 31 19 AM

**Review by nadiakiamilev — APPROVED** [review]

**Comment by neokry** [comment]
Added some helper text to the paused auctions per @isaaczaak 
Could you review these changes when you have a chance @nadiakiamilev . Everything new is in the `AuctionPaused.tsx` file in the `auction` module.

text when the paused proposal is found:
Screen Shot 2023-03-16 at 12 44 07 PM

text whent he paused proposal is not found:
Screen Shot 2023-03-16 at 12 44 33 PM

**Pull request merged**
