### PR TITLE
Add proposal template droposal

### LINKED ISSUE #151: [PROP TEMPLATE] Droposal: Single Edition (ERC-721)
https://zora-starter-kit.vercel.app/create

https://github.com/0xTranqui/zora-starter-kit

### PR DESCRIPTION
**Pull request by neokry**
## Description

Create droposal prop template

## Motivation & context

closes #151 

## Code review

- are transactions being built properly
- is form validation working
- should the form be compacted

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Comment by isaaczaak** [comment]
Droposal template feedback:

**Selection page**
1. Add a background to the icon - maybe we could use Blue this time? 
  - Icon `#00A3FF`
  - Background `#E5F6FF`

2. Subtext: “Create a droposal for a Single-edition ERC721 collection” 

**Proposal creation page**
1. On the proposal creation page, add a help text to the top of the page just underneath the dropdown selector “This droposal uses the ZORA 721 Contract. [Lean more](https://docs.zora.co/docs/smart-contracts/creator-tools/ZoraNFTCreator)”
2. Update subtext for Price to “Zora charges a small flat fee 0.000777 ETH per NFT minted to collectors. [Learn more](https://support.zora.co/en/articles/4981037-zora-mint-collect-fees) ”

**Comment by isaaczaak** [comment]
Disable "Add transaction to queue" button when file is still uploading

**Comment by 0xrawtoast** [comment]
I had success with uploading all three file types (IMG, VID, AUD), and each time, they would correctly display 'n transactions queued'. 

However, when it did get added to the queue, it would clear out the whole create form. It would show like this screenshot below 

Screen Shot 2023-04-25 at 7 53 03 am

**Review by isaaczaak — APPROVED** [review]
I was able to successfully add a droposal template as well as a multi-tx proposal

tested ✅

**Review by ninazo — APPROVED** [review]

**Pull request merged**
