### PR TITLE
Simulate L2 transactions

### PR DESCRIPTION
**Pull request by neokry**
## Description

Adds L2 tx simulations

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [ ] Any new and existing tests pass locally with my changes
- [ ] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Comment by isaaczaak** [comment]
is it possible to also add simulations for Base Mainnet and OP Mainnet txs? @neokry

**Comment by neokry** [comment]
> is it possible to also add simulations for Base Mainnet and OP Mainnet txs? @neokry

it is but I didn't know if we wanted to push this out asap or not. I can add simulation for those networks as well if it's not urgent

**Comment by neokry** [comment]
updated to include all L2 mainnets and testnets @isaaczaak . looking at tenderly docs these should all be supported now

**Comment by isaaczaak** [comment]
@neokry Looks like Tenderly did not pick up this invalid transaction:

https://testnet-nouns-builder-git-zora-simulations-nouns-builder.vercel.app/dao/zora-goerli/0xf0be5410497e4a71345e4dada103b56381631d58/vote/1

I used the same Crowdfund address that MODEL-WIP was trying to use and i was able to successfully submit the prop.

**Pull request merged**
