### PR TITLE
Salief/add proposal guidelines page

### PR DESCRIPTION
**Pull request by salieflewis**
## Description

Adds a Proposal Guidelines page featuring the words in [this](https://docs.google.com/document/d/13LlMLRsCMf_izt6O-11VMhI0NfOFO2I0iwVPEW1Zilg/edit) document.

## Motivation & context

Surfaces information that was previously only available on Google Docs.

## Code review

I placed the link to this page in the footer besides the Documentation link. Not sure if this is the best place for it, open to suggestions.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Comment by isaaczaak** [comment]
we could also add the link to the proposal creation flow :)

**Comment by salieflewis** [comment]
> we could also add the link to the proposal creation flow :)

I thought about this, but wasn't exactly sure where it should go.

**Comment by isaaczaak** [comment]
> > we could also add the link to the proposal creation flow :)
> 
> I thought about this, but wasn't exactly sure where it should go.


quick mock! this step is after adding the transactions to queue


image

**Comment by neokry** [comment]
what do you think about calling the route `guidelines` instead of `propguidelines` @salieflewis . other than that it looks good!

**Comment by neokry** [comment]
also we should add this to the homepage footer. the footer component is only on non homepage routes

**Comment by salieflewis** [comment]
> what do you think about calling the route `guidelines` instead of `propguidelines` @salieflewis . other than that it looks good!

Guidelines makes sense. I will make that change.

**Comment by salieflewis** [comment]
> also we should add this to the homepage footer. the footer component is only on non homepage routes

Noted. And @isaaczaak happy to put it also where you suggested. So changes to made, for clarification.

1. Change the route to `guidelines.tsx` and associated stylesheet, component name...
2. Add a link to the route to the homepage footer (and keep it on the non-homepage footer as well?)
3. Add a link to the proposal review section that would open a new tab and take prop writers to this page.

cc: @neokry @isaaczaak

**Comment by neokry** [comment]
Changes looks good so far! final thing I think we can reduce the padding slightly on the review page to something like this @salieflewis :

Screen Shot 2023-06-23 at 10 48 08 AM

makes it a bit easier to visually separate the title + subtitle from the form. this is a change to the `CreateProposalHeading` Stack pb property. once this is done we can merge! thank you

**Comment by salieflewis** [comment]
> Changes looks good so far! final thing I think we can reduce the padding slightly on the review page to something like this @salieflewis :
> 
> Screen Shot 2023-06-23 at 10 48 08 AM
> 
> makes it a bit easier to visually separate the title + subtitle from the form. this is a change to the `CreateProposalHeading` Stack pb property. once this is done we can merge! thank you

Ok, done! Lmk if there is anything else or need me to adjust it.

**Comment by salieflewis** [comment]
> > Changes looks good so far! final thing I think we can reduce the padding slightly on the review page to something like this @salieflewis :
> > Screen Shot 2023-06-23 at 10 48 08 AM
> > makes it a bit easier to visually separate the title + subtitle from the form. this is a change to the `CreateProposalHeading` Stack pb property. once this is done we can merge! thank you
> 
> Ok, done! Lmk if there is anything else or need me to adjust it.

cc: @neokry

**Review by nadiakiamilev — COMMENTED** [review]
looks good! can we remove the pnpm lock file changes from this PR?

**Review by neokry — APPROVED** [review]

**Pull request merged**
