### PR TITLE
Add replace artwork proposal template

### LINKED ISSUE #171: [PROP TEMPLATE] Update artwork - "Replace artwork"
User story
As a user, I want to submit a artwork update proposal, so that the DAO can vote on changing the token artwork onchain.

Refer to this proposal:

https://nouns.build/dao/0x96e396e66087b2b9dcad36fd473e1b049df18998/vote/0x409989b8b00a8f06ddb210aa7ac49ebcb79253879af4469a5aeafc53ef54e8b6

### PR DESCRIPTION
**Pull request by neokry**
## Description

Adds new proposal template to replace DAO artwork

## Motivation & context

closes #171 

## Code review

tbd

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Review by isaaczaak — CHANGES_REQUESTED** [review]
Change "Upgrade Artwork" to "Replace Artwork"

**Review by isaaczaak — APPROVED** [review]
tested ✅

**Comment by taayyohh** [comment]
@neokry Using the advanced playground to preview artwork after uploading artwork to replace does not work for me -- not sure if you're experiencing this as well? The modal opens, but traits as filters never load and generate button is disabled

**Comment by taayyohh** [comment]
Re-uploading artwork to fix a validation error does not retrigger validation or update the layers -- I think this is related to a known re-uploading bug that also exists in the create flow, so may be non blocking, but did want to flag

**Comment by taayyohh** [comment]
can we make this conditional to only render on mainnet?
image

**Comment by taayyohh** [comment]
I think DAOs that have not yet upgrade to 1.2.0 may not be able to execute this transaction?

https://nouns-builder-pbnh20axx-ourzora.vercel.app/dao/0x3bf599ad351ff7bdac0490160f76c8752edec6c0/ have attempted to replace this artwork but the transaction simulation fails each time. If this is the case, we may want to add this bit of functionality that exists in the airdrop feature
image


https://dashboard.tenderly.co/public/zora/nouns-builder-public/fork-simulation/96fc4367-4874-4231-8a0c-f45cfaa76a22

**Comment by neokry** [comment]
> Re-uploading artwork to fix a validation error does not retrigger validation or update the layers -- I think this is related to a known re-uploading bug that also exists in the create flow, so may be non blocking, but did want to flag

thanks for flagging! going to do a follow up pr after this with some bugfixes for the artwork uploader

**Comment by neokry** [comment]
> @neokry Using the advanced playground to preview artwork after uploading artwork to replace does not work for me -- not sure if you're experiencing this as well? The modal opens, but traits as filters never load and generate button is disabled

me and @isaaczaak can't seem to reproduce this issue. can you send the artwork folder you are testing with

**Review by taayyohh — APPROVED** [review]
Working as expected! Looks great

**Pull request merged**
